spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?currentSchema=toeic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  auth:
    token-secret: lNLp8m5m86mRQLgNU7UnhGqfBbNdNYAM45YOFwZmP1w=
    refresh-token-expiration-milliseconds: 1209600000  # 14 days
    access-token-expiration-milliseconds: 86400000  # 24 hours
    reset-token-expiration-milliseconds: 300000
    register-token-expiration-milliseconds: 300000