spring:
  datasource:
    url: jdbc:postgresql://dpg-d5fval95pdvs73fjm5q0-a.singapore-postgres.render.com:5432/word_note
    username: word_note_user
    password: tA54fPC3lEUl6y2amKKLaRqpXiwINHvi
    driver-class-name: org.postgresql.Driver

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000

app:
  auth:
    token-secret: lNLp8m5m86mRQLgNU7UnhGqfBbNdNYAM45YOFwZmP1w=
    refresh-token-expiration-milliseconds: 1209600000  # 14 days
    access-token-expiration-milliseconds: 86400000  # 24 hours
    reset-token-expiration-milliseconds: 300000
    register-token-expiration-milliseconds: 300000